# Generated by Django 5.2.17 on 2026-08-12 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_studentresult_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_embed_code',
            field=models.TextField(blank=True, help_text='Альтернатива ссылке: вставьте код <iframe> из кнопки «Поделиться → Встроить» на YouTube или Vimeo. ', verbose_name='Код встраивания (iframe)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube или Vimeo (напр. https://www.youtube.com/watch?v=XXX или https://vimeo.com/12345).', verbose_name='Видео (YouTube/Vimeo)'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Открыт')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Прогресс урока',
                'verbose_name_plural': 'Прогресс уроков',
                'ordering': ['-opened_at'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
