# Generated by Django 5.2.17 on 2026-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_video_embed_code_alter_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_embed_code',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube видео (например: https://www.youtube.com/watch?v=dQw4w9WgXcQ или https://youtu.be/dQw4w9WgXcQ)', verbose_name='Видео YouTube'),
        ),
    ]
